# Generated by Django 3.2.4 on 2021-06-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3uservers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listservers',
            name='contentm3u',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listservers',
            name='idServer',
            field=models.DecimalField(decimal_places=0, default=123, max_digits=3),
            preserve_default=False,
        ),
    ]
