# Generated by Django 3.2.4 on 2021-06-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m3uservers', '0004_listservers_contentm3u2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listservers',
            name='contentm3u',
        ),
    ]
