# Generated by Django 3.2.4 on 2021-06-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3uservers', '0005_remove_listservers_contentm3u'),
    ]

    operations = [
        migrations.CreateModel(
            name='canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idm3u', models.DecimalField(decimal_places=0, max_digits=3)),
                ('idCanal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('nameCanal', models.CharField(max_length=1024)),
                ('nameGroup', models.CharField(max_length=1024)),
                ('urlCanal', models.CharField(max_length=1024)),
            ],
        ),
    ]
