# Generated by Django 3.2.4 on 2021-06-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3uservers', '0006_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='idCanal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='canal',
            name='idm3u',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listservers',
            name='idServer',
            field=models.IntegerField(),
        ),
    ]
