# Generated by Django 3.2.4 on 2021-06-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3uservers', '0007_auto_20210630_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listservers',
            name='addressServer',
        ),
        migrations.RemoveField(
            model_name='listservers',
            name='ipNameServer',
        ),
        migrations.AddField(
            model_name='listservers',
            name='urlServer',
            field=models.CharField(default=123, max_length=1024),
            preserve_default=False,
        ),
    ]
